import numpy as np
import netCDF4 as nc

# Define dimensions similar to your tmin file
lon_size = 919
lat_size = 499
time_size = 3988

# Create arrays for latitude, longitude, and time
latitudes = np.linspace(26, 31, lat_size)
longitudes = np.linspace(80, 88, lon_size)
time_values = np.arange(time_size)

# Create a new NetCDF file
nc_file = nc.Dataset('dummy_tmax_climpact_data.nc', 'w', format='NETCDF4')

# Create dimensions
nc_file.createDimension('lon', lon_size)
nc_file.createDimension('lat', lat_size)
nc_file.createDimension('Time', time_size)
nc_file.createDimension('transverse_mercator', 1)  # Following your example, though unused

# Create variables
lon = nc_file.createVariable('lon', 'f8', ('lon',))
lat = nc_file.createVariable('lat', 'f8', ('lat',))
time = nc_file.createVariable('time', 'f8', ('Time',))
tmax = nc_file.createVariable('tmax', 'f4', ('Time', 'lat', 'lon'), fill_value=-3.402823e+38)
transverse_mercator = nc_file.createVariable('transverse_mercator', 'i4', ('transverse_mercator',))

# Assign attributes to variables
lon.long_name = "Longitude"
lon.standard_name = "longitude"
lon.units = "degrees_east"
lon.axis = "X"

lat.long_name = "Latitude"
lat.standard_name = "latitude"
lat.units = "degrees_north"
lat.axis = "Y"

time.long_name = "Time"
time.standard_name = "time"
time.units = "days since 1899-12-30"
time.calendar = "standard"
time.axis = "T"

tmax.long_name = "Daily Maximum Temperature"
tmax.standard_name = "air_temperature"
tmax.units = "C"
tmax.coordinates = "lon lat"
tmax.grid_mapping = "transverse_mercator"

transverse_mercator.grid_mapping_name = "transverse_mercator"
transverse_mercator.longitude_of_central_meridian = 87.0
transverse_mercator.latitude_of_projection_origin = 0.0
transverse_mercator.scale_factor_at_central_meridian = 0.9996
transverse_mercator.false_easting = 500000.0
transverse_mercator.false_northing = 0.0

# Assign global attributes
nc_file.Conventions = "CF-1.6"
nc_file.Source_Software = "Generated by Python script"
nc_file.title = "Daily Maximum Temperature Data for Nepal (Dummy)"
nc_file.history = "File created on August 12, 2024"
nc_file.institution = "Pulchowk Campus, IOE"
nc_file.source = "Simulated data for testing"
nc_file.references = "Provide any references or data sources here"
nc_file.comment = "This dataset contains daily maximum temperature data for Nepal as a dummy file."

# Assign data to variables
lon[:] = longitudes
lat[:] = latitudes
time[:] = time_values
tmax[:, :, :] = np.random.uniform(20, 40, (time_size, lat_size, lon_size))

# Close the file
nc_file.close()

print("Dummy tmax NetCDF file created: dummy_tmax_climpact_data.nc")
